GET http://localhost:3001/api/blogs/
###
GET http://localhost:3001/api/blogs/642044e2c37244fa984bd733
###
DELETE http://localhost:3001/api/blogs/642044e2c37244fa984bd733
###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
  "title": "How to make money and win friends",
  "author": "Dale Carnegie",
  "url": "https://www.google.com/",
  "likes": 3
}
### upload multiple
POST http://localhost:3001/api/blogs/multiple
Content-Type: application/json

{
  "blogs": [
    {
      "title": "A Beginner's Guide to JavaScript",
      "author": "John Smith",
      "url": "https://www.example.com/beginners-guide-to-javascript",
      "likes": 12
    },
    {
      "title": "10 Tips for Writing Better Code",
      "author": "Jane Doe",
      "url": "https://www.example.com/10-tips-for-writing-better-code",
      "likes": 25
    },
    {
      "title": "The Future of Web Development",
      "author": "Alex Johnson",
      "url": "https://www.example.com/future-of-web-development",
      "likes": 18
    },
    {
      "title": "How to Build a RESTful API",
      "author": "Sarah Lee",
      "url": "https://www.example.com/building-a-restful-api",
      "likes": 8
    },
    {
      "title": "Introduction to React.js",
      "author": "Mike Brown",
      "url": "https://www.example.com/introduction-to-react-js",
      "likes": 35
    },
    {
      "title": "10 Ways to Speed Up Your Website",
      "author": "Lisa Kim",
      "url": "https://www.example.com/10-ways-to-speed-up-your-website",
      "likes": 17
    },
    {
      "title": "Best Practices for Node.js Development",
      "author": "David Jones",
      "url": "https://www.example.com/best-practices-for-node-js-development",
      "likes": 22
    },
    {
      "title": "Creating Custom WordPress Themes",
      "author": "Emily Davis",
      "url": "https://www.example.com/creating-custom-wordpress-themes",
      "likes": 11
    },
    {
      "title": "Introduction to Machine Learning",
      "author": "Chris Lee",
      "url": "https://www.example.com/introduction-to-machine-learning",
      "likes": 29
    },
    {
      "title": "How to Secure Your Web Application",
      "author": "Brian Johnson",
      "url": "https://www.example.com/how-to-secure-your-web-application",
      "likes": 14
    }
  ]
}

### 
PUT http://localhost:3001/api/blogs/642044e2c37244fa984bd733
Content-Type: application/json

{
  "title": "How to Secure Your Web Application",
  "author": "Brian Johnson",
  "url": "https://www.example.com/how-to-secure-your-web-application",
  "likes": 14
}
