GET http://localhost:3001/api/blogs/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2UiLCJpZCI6IjY0MjM5MTI1Yjc5YWU1YTEzMjBhZWRmZiIsImlhdCI6MTY4MDA1MjUxOSwiZXhwIjoxNjgwMDYzMzE5fQ.mnuMEy4aBw8i3Pdp9tKGCC0cVpipZwuDoIHfgH1pAWg

###
GET http://localhost:3001/api/blogs/64239162b79ae5a1320aee06
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2UiLCJpZCI6IjY0MjM5MTI1Yjc5YWU1YTEzMjBhZWRmZiIsImlhdCI6MTY4MDA1MjUxOSwiZXhwIjoxNjgwMDYzMzE5fQ.mnuMEy4aBw8i3Pdp9tKGCC0cVpipZwuDoIHfgH1pAWg

###
DELETE http://localhost:3001/api/blogs/64239162b79ae5a1320aee06
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2UiLCJpZCI6IjY0MjM5MTI1Yjc5YWU1YTEzMjBhZWRmZiIsImlhdCI6MTY4MDA1MjUxOSwiZXhwIjoxNjgwMDYzMzE5fQ.mnuMEy4aBw8i3Pdp9tKGCC0cVpipZwuDoIHfgH1pAWg

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2UiLCJpZCI6IjY0MjM5MTI1Yjc5YWU1YTEzMjBhZWRmZiIsImlhdCI6MTY4MDA1MjUxOSwiZXhwIjoxNjgwMDYzMzE5fQ.mnuMEy4aBw8i3Pdp9tKGCC0cVpipZwuDoIHfgH1pAWg

{
  "title": "How to make money and win friends",
  "author": "Dale Carnegie",
  "url": "https://www.google.com/",
  "likes": 3
}
### upload multiple
POST http://localhost:3001/api/blogs/multiple
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2UiLCJpZCI6IjY0MjM5MTI1Yjc5YWU1YTEzMjBhZWRmZiIsImlhdCI6MTY4MDA1MjUxOSwiZXhwIjoxNjgwMDYzMzE5fQ.mnuMEy4aBw8i3Pdp9tKGCC0cVpipZwuDoIHfgH1pAWg

{
  "blogs": [
    {
      "title": "A Beginner's Guide to JavaScript",
      "author": "John Smith",
      "url": "https://www.example.com/beginners-guide-to-javascript",
      "likes": 12
    },
    {
      "title": "10 Tips for Writing Better Code",
      "author": "Jane Doe",
      "url": "https://www.example.com/10-tips-for-writing-better-code",
      "likes": 25
    },
    {
      "title": "The Future of Web Development",
      "author": "Alex Johnson",
      "url": "https://www.example.com/future-of-web-development",
      "likes": 18
    },
    {
      "title": "How to Build a RESTful API",
      "author": "Sarah Lee",
      "url": "https://www.example.com/building-a-restful-api",
      "likes": 8
    },
    {
      "title": "Introduction to React.js",
      "author": "Mike Brown",
      "url": "https://www.example.com/introduction-to-react-js",
      "likes": 35
    },
    {
      "title": "10 Ways to Speed Up Your Website",
      "author": "Lisa Kim",
      "url": "https://www.example.com/10-ways-to-speed-up-your-website",
      "likes": 17
    },
    {
      "title": "Best Practices for Node.js Development",
      "author": "David Jones",
      "url": "https://www.example.com/best-practices-for-node-js-development",
      "likes": 22
    },
    {
      "title": "Creating Custom WordPress Themes",
      "author": "Emily Davis",
      "url": "https://www.example.com/creating-custom-wordpress-themes",
      "likes": 11
    },
    {
      "title": "Introduction to Machine Learning",
      "author": "Chris Lee",
      "url": "https://www.example.com/introduction-to-machine-learning",
      "likes": 29
    },
    {
      "title": "How to Secure Your Web Application",
      "author": "Brian Johnson",
      "url": "https://www.example.com/how-to-secure-your-web-application",
      "likes": 14
    }
  ]
}

### 
PUT http://localhost:3001/api/blogs/5a422a851b54a676234d17f7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2UiLCJpZCI6IjY0MjM5MTI1Yjc5YWU1YTEzMjBhZWRmZiIsImlhdCI6MTY4MDA1MjUxOSwiZXhwIjoxNjgwMDYzMzE5fQ.mnuMEy4aBw8i3Pdp9tKGCC0cVpipZwuDoIHfgH1pAWg

{
  "title": "How to Secure Your Web Application",
  "author": "Brian Johnson",
  "url": "https://www.example.com/how-to-secure-your-web-application",
  "likes": 14
}

### make user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "mike",
  "password": "12345",
  "name": "mike!"
}

### get JWT for given credentials
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "mike",
  "password": "12345"
}
### get a list of users
GET http://localhost:3001/api/users